/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 stone.gltf 
Author: The British Museum (https://sketchfab.com/britishmuseum)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/the-rosetta-stone-1e03509704a3490e99a173e53b93e282
Title: The Rosetta Stone
*/

import React, {useRef} from 'react'
import { useGLTF } from '@react-three/drei'

export default function Stone() {
  const meshRef = useRef();
  const { nodes, materials } = useGLTF('stone/stone.gltf')
  
  return (
    <group rotation={[-Math.PI / 2, 0, 0]}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            ref={meshRef}
            material={materials["fiveHundred_baseColor"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('stone/stone.gltf')
